version: '3.5'

services:

  postgres:
    image: postgres
    container_name: postgres1
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "p4ssw0rd" 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data  
     
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1  
    restart: unless-stopped  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - "8200:80"
    depends_on:
      - postgres
    volumes:
       - pgadmin:/var/lib/pgadmin
       
volumes:
  pgadmin:

