services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
     
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL="admin@example.com"
      - PGADMIN_DEFAULT_PASSWORD="p4ssw0rd"
    ports:
      - "8200:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
